export const arrayItems = [
  {
    name: "ANSWER QUESTIONS",
    id: "q&a",
    description: "Answer questions based on existing knowledge",
    option: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 1000,
      top_p: 1,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Create a Quiz",
    id: "grammerCorrection",
    description: "Create a quiz based on Syllabus.",
    option: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 1000,
      top_p: 1,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Physics",
    id: "summary",
    description: "Elaborate a physics concept in simple terms.",
    option: {
      model: "text-davinci-003",
      temperature: 0.7,
      max_tokens: 640,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Biology",
    id: "translate",
    description: "Elaborate a biology concept into simple terms.",
    option: {
      model: "text-davinci-003",
      temperature: 0.3,
      max_tokens: 1000,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "C++",
    id: "movieToEmoji",
    description: "Elaborate C++ Oops concept into simple terms.",
    option: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 1000,
      top_p: 1,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Explain code",
    id: "explainCode",
    description: "Explain a complicated piece of code.",
    option: {
      model: "code-davinci-002",
      temperature: 0,
      max_tokens: 640,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "JavaScript to Python",
    id: "jstopy",
    description: "Convert simple JavaScript expressions into Python.",
    option: {
      model: "code-davinci-002",
      temperature: 0,
      max_tokens: 640,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
];
